### PR TITLE
Add Year in Hardfork Secsion

### PR DESCRIPTION
**Pull request by messiisgreat**
## Checkout Points

- [ ] Check if all of years are correct
- [ ] Check if years are included in every locales.

image

image

image

### CODE REVIEW

**Review by Maxnflaxl — CHANGES_REQUESTED** [review]
the icons aren't there anymore

**Comment by messiisgreat** [comment]
> the icons aren't there anymore

Sorry, What do you mean?

**Comment by Maxnflaxl** [comment]
compare your screenshot(s) above with this:

image

**Comment by messiisgreat** [comment]
Sorry, looks like this below.
First screenshots were because of some issue.
It's running properly.

image

**Review by Maxnflaxl — APPROVED** [review]

**Pull request merged**
